version: '3.7'
services:
        database:
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: company
                ports:
                        - 3307:3306
                volumes:
                        - ./init.sql:/DockerCompseFile/init.sql

        application:
                image: springbootwithjpahibernate
                
                ports:
                        - 8080:8080
                depends_on:
                        - database
